version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    groups:
      python-production:
        patterns:
          - "*"
